### ISSUE TITLE
tracker not working 

### ISSUE THREAD

**Issue by srivatsan18** [murtazahassan/OpenCV-Python-Tutorials-for-Beginners#1]
Even after install opencv-contrib-python tracker function is showing attribute error AttributeError: module 'cv2.cv2' has no attribute 'TrackerMOSSE_create'

I am using Windows 10 
Opencv -v 4.0
python 3

**Comment by MaximTkachev1** [comment]
I'm not very good with opencv but try this: tracker = cv2.legacy.TrackerMOSSE_create()

if that's what you wrote, then I don't know what's wrong

**Comment by MaximTkachev1** [comment]
I just noticed that the question is already closed
